SWIDEA_SITE/SWIDEA/SWIDEA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ideas.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/SWIDEA/ideas/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'ideas'

urlpatterns = [
    path('', view = views.idea_list, name='idea_list'),
    path('idea_create/', view = views.idea_create, name='idea_create'),
    path('<int:pk>/', view=views.idea_detail, name='idea_detail'),
    path('<int:pk>/idea_update', view=views.idea_update, name='idea_update'),
    path('<int:pk>/idea_delete', view=views.idea_delete, name='idea_delete'),
    path('devt_list', view = views.devt_list, name='devt_list' ),
    path('devt_create/', view=views.devt_create, name='devt_create'),
    path('<int:pk>/devt_detail', view=views.devt_detail, name='devt_detail'),
    path('<int:pk>/devt_update', view=views.devt_update, name='devt_update'),
    path('<int:pk>/devt_delete', view=views.devt_delete, name='devt_delete'),


]

SWIDEA_SITE/SWIDEA/ideas/models.py
from django.db import models

# Create your models here.
class Devtool(models.Model):
    name = models.CharField(verbose_name='이름', max_length=50)
    kind = models.CharField(verbose_name='종류', max_length=100)
    description = models.TextField(verbose_name='설명')

    def __str__(self):
        return self.name

class Idea(models.Model):
    title = models.CharField(verbose_name='제목', max_length=100)
    image = models.ImageField(upload_to="poster", null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    interest = models.IntegerField(verbose_name='관심도')
    devtool = models.ForeignKey(Devtool, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

SWIDEA_SITE/SWIDEA/ideas/forms.py
from django import forms
from .models import Idea,Devtool

class IdeaForm(forms.ModelForm):
    
    class Meta:
        model = Idea
        fields = '__all__'

class DevtoolForm(forms.ModelForm):
    
    class Meta:
        model = Devtool
        fields = '__all__'

SWIDEA_SITE/SWIDEA/ideas/views.py
from urllib import request
from django.shortcuts import render, get_object_or_404, redirect
from .models import Devtool, Idea
from .forms import IdeaForm, DevtoolForm

# Create your views here.
def idea_list(request):
    ideas = Idea.objects.all()
    ctx = {'ideas' : ideas}

    return render(request, template_name='idea_list.html', context=ctx)

def idea_create(request):
    if request.method == 'POST': 
        form = IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('ideas:idea_list')
        # idea = Idea()
        # idea.title = request.POST['title']
        # idea.image = request.FILES['poster']
        # idea.content = request.POST['content']
        # idea.interest = request.POST['interest']
        # devtool_name = request.POST['devtool']
        # devt = Devtool.objects.get(name=devtool_name)
        # idea.devtool = devt
        # idea.save()
        # return redirect('ideas:idea_list')
    else: #request.method == 'GET'
        form = IdeaForm()
        ctx = {'form' : form}

        return render(request, template_name='idea_create.html', context=ctx)

def idea_detail(request, pk):
    idea = Idea.objects.get(id=pk)
    ctx = {'idea' : idea}

    return render(request, template_name='idea_detail.html', context=ctx)

def idea_update(request, pk):
    idea = get_object_or_404(Idea, id=pk)

    if request.method == 'POST':
        form = IdeaForm(request.POST, instance=idea)
        if form.is_valid():
            form.save()
            return redirect('ideas:idea_detail', pk)
    else:
        form = IdeaForm(instance=idea)
        ctx = {'form' : form, 'idea': idea}
        
        return render(request, template_name='idea_create.html', context=ctx)

def idea_delete(request, pk):
    idea = Idea.objects.get(id=pk)
    idea.delete()
    return redirect('ideas:idea_list')

def devt_create(request):
    if request.method == 'POST': 
        devt = Devtool()
        devt.name = request.POST['name']
        devt.kind = request.POST['kind']
        devt.description = request.POST['description']
        devt.save()

        return redirect('ideas:devt_list')
    else: #request.method == 'GET'

        return render(request, template_name='devt_create.html')

def devt_list(request):
    devts = Devtool.objects.all()
    ctx = {'devts' : devts}

    return render(request, template_name='devt_list.html', context=ctx)

def devt_detail(request, pk):
    devt = Devtool.objects.get(id=pk)
    ideas = devt.idea_set.all()
    ctx = {
        'devt' : devt,
        'ideas' : ideas,
    }

    return render(request, template_name = 'devt_detail.html', context=ctx)

def devt_update(request,pk):
    devt = get_object_or_404(Devtool, id=pk)

    if request.method == 'POST':
        devt.name = request.POST['name']
        devt.kind = request.POST['kind']
        devt.description = request.POST['description']
        devt.save()
        
        return redirect('ideas:devt_detail', pk)
    else:
        # form = DevtoolForm(instance = devt)
        ctx = {'devt':devt}

        return render(request, template_name='devt_create.html', context=ctx)

def devt_delete(request, pk):
    devt = get_object_or_404(Devtool, id=pk)
    devt.delete()
    return redirect('ideas:devt_list')

SWIDEA_SITE/SWIDEA/ideas/templates/devt_create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포스트 작성</title>
  </head>

  <body>
    <form action="" method="post">
      {% csrf_token %}
      <div>
        <label for="name">>> 이름</label><br />
        <input type="text" name="name" id="name" value="{% if devt.name %}{{devt.name}}{% endif %}"/>
      </div>
      <div>
        <label for="kind">>> 종류</label><br />
        <input type="text" name="kind" id="kind" value="{% if devt.kind %}{{devt.kind}}{% endif %}"/>
      </div>
      <div>
        <label for="description">>> 개발툴 설명</label><br />
        <textarea name="description" id="content" cols="30" rows="10">{% if devt.description %}{{devt.description}}{% endif %}</textarea>
      </div>
      <input type="submit" value="SUBMIT" />
    </form>
  </body>
</html>

SWIDEA_SITE/SWIDEA/ideas/templates/devt_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포스트 상세 정보</title>
  </head>

  <body>
    <h2><a href="{% url 'ideas:idea_create'%}">아이디어 등록</a></h2>
    <h2><a href="{% url 'ideas:idea_list'%}">아이디어 관리</a></h2>
    <h2><a href="{% url 'ideas:devt_create'%}">개발툴 등록</a></h2>
    <h2><a href="{% url 'ideas:devt_list'%}">개발툴 관리</a></h2>

    <h1>{{ devt.name }}</h1>
    <p>{{ devt.kind }}</p>
    <p>{{ devt.description }}</p>

    <p>얻을 수 있는 SW 목록</p>
    {% for idea in ideas %}
        <p><a href="{% url 'ideas:idea_detail' idea.id%}">{{idea.title}}</a></p>
    {% endfor %}
    

    <a href="{% url 'ideas:devt_list' %}">목록</a>
    <a href="{% url 'ideas:devt_update' devt.id %}">수정</a>
    <a href="{% url 'ideas:devt_delete' devt.id %}">삭제</a>



  </body>
</html>

SWIDEA_SITE/SWIDEA/ideas/templates/devt_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=divice-width" />
    <title>글 리스트</title>
  </head>
  <body>
    <h2><a href="{% url 'ideas:idea_create'%}">아이디어 등록</a></h2>
    <h2><a href="{% url 'ideas:idea_list'%}">아이디어 관리</a></h2>
    <h2><a href="{% url 'ideas:devt_create'%}">개발툴 등록</a></h2>
    <h2><a href="{% url 'ideas:devt_list'%}">개발툴 관리</a></h2>

    {%for devt in devts%}
    <h2><a href="{% url 'ideas:devt_detail' devt.id%}">{{devt.name}}</a></h2>
    <h4>{{devt.kind}}</h4>
    <h4>{{devt.description}}</h4>

    {%endfor%}
  </body>
</html>

SWIDEA_SITE/SWIDEA/ideas/templates/idea_create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포스트 작성</title>
  </head>

  <body>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div>
        <label for="title">>> 아이디어명</label><br />
        <input type="text" name="title" id="title" value="{% if idea.title %}{{idea.title}}{% endif %}"/>
      </div>
      <div>
        <label>>> 대표 사진 </label> <br />
        <input name="poster" type="file" maxlength="255" value="{% if idea.image %}{{idea.image.url}}{% endif %}">
      </div>
      <div>
        <label for="content">>> 아이디어 설명</label><br />
        <textarea name="content" id="content" cols="30" rows="10">{% if idea.content %}{{idea.content}}{% endif %}</textarea>
      </div>
      <div>
        <label for="interest">>> 아이디어 관심도</label><br />
        <input type="text" name="interest" id="interest" value="{% if idea.interest %}{{idea.interest}}{% endif %}"/>
      </div>
      <div>
        <label>>> 예상 개발툴</label><br />
        <span>{{form.devtool}}</span>
      </div>
      
      <input type="submit" value="SUBMIT" />
    </form>
  </body>
</html>

SWIDEA_SITE/SWIDEA/ideas/templates/idea_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포스트 상세 정보</title>
  </head>

  <body>
    <h2><a href="{% url 'ideas:idea_create'%}">아이디어 등록</a></h2>
    <h2><a href="{% url 'ideas:idea_list'%}">아이디어 관리</a></h2>
    <h2><a href="{% url 'ideas:devt_create'%}">개발툴 등록</a></h2>
    <h2><a href="{% url 'ideas:devt_list'%}">개발툴 관리</a></h2>

    <div class=list-poster>
        {% if idea.image %}
            <img src="{{idea.image.url}}" height="220" width="160">
        {% else %}
          <img src="https://picsum.photos/seed/{{idea.id}}/160/220?">
        {% endif %}
    </div>
    <h1>{{ idea.title }}</h1>
    <p>1)아이디어 관심도: <br>{{ idea.interest }}</p>
    <p>2)예상 개발 툴: <br>{{ idea.devtool }}</p>
    <p>3)아이디어 설명: <br>{{ idea.content }}</p>    

    <a href="{% url 'ideas:idea_list' %}">목록</a>
    <a href="{% url 'ideas:idea_update' idea.id %}">수정</a>
    <a href="{% url 'ideas:idea_delete' idea.id %}">삭제</a>



  </body>
</html>

SWIDEA_SITE/SWIDEA/ideas/templates/idea_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=divice-width" />
    <title>글 리스트</title>
  </head>
  <body>
    
    <h2><a href="{% url 'ideas:idea_create'%}">아이디어 등록</a></h2>
    <h2><a href="{% url 'ideas:idea_list'%}">아이디어 관리</a></h2>
    <h2><a href="{% url 'ideas:devt_create'%}">개발툴 등록</a></h2>
    <h2><a href="{% url 'ideas:devt_list'%}">개발툴 관리</a></h2>

    {%for idea in ideas%}
    <div class=list-poster>
        {% if idea.image %}
            <img src="{{idea.image.url}}" height="220" width="160">
        {% else %}
          z
        {% endif %}
    </div>
    <h2><a href="{% url 'ideas:idea_detail' idea.id%}">{{idea.title}}</a></h2>
    <h4>예상 개발 툴 : {{idea.devtool}}</h4>
    <h4>아이디어 관심도 : {{idea.interest}}</h4>
    <br />

    {%endfor%}
  </body>
</html>