myMovieReviews/MOVIE/MOVIE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
]

myMovieReviews/MOVIE/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', view = views.review_list, name='list'),
    path('<int:pk>/', view=views.review_detail, name='detail'),
    path('create/', view=views.review_create, name='create'),
    path('<int:pk>/update', view=views.review_update, name='update'),
    path('<int:pk>/delete', view=views.review_delete, name='delete'),
]

myMovieReviews/MOVIE/reviews/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(verbose_name='제목', max_length=100)
    year = models.IntegerField(verbose_name='개봉년도')
    genre = models.CharField(verbose_name='장르', max_length=50)
    rating = models.CharField(verbose_name='별점', max_length=10)
    runningTime = models.IntegerField(verbose_name='러닝타임')
    review = models.TextField(verbose_name='리뷰')
    director = models.CharField(verbose_name='감독', max_length=50)
    actor = models.CharField(verbose_name='배우', max_length=100)

    def __str__(self):
        return self.title

myMovieReviews/MOVIE/reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = '__all__'

myMovieReviews/MOVIE/reviews/views.py
from pdb import post_mortem
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review
from .forms import ReviewForm

# Create your views here.
def review_list(request):
    reviews = Review.objects.all()
    ctx = {'reviews' : reviews}

    return render(request, template_name='list.html', context=ctx)

def review_detail(request, pk):
    review = Review.objects.get(id=pk)
    ctx = {'review' : review}

    return render(request, template_name='detail.html', context=ctx)

def review_create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('reviews:list')
    else:
        form = ReviewForm()
        ctx = {'form' : form}

        return render(request, template_name='create.html', context=ctx)

def review_update(request, pk):
    review = get_object_or_404(Review, id=pk)

    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('reviews:detail', pk)
    else:
        form = ReviewForm(instance=review)
        ctx = {'form' : form}
        
        return render(request, template_name='create.html', context=ctx)

def review_delete(request, pk):
    review = get_object_or_404(Review, id=pk)
    review.delete()
    return redirect('reviews:list')


    

myMovieReviews/MOVIE/reviews/templates/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포스트 작성</title>
  </head>

  <body>
    <form action="" method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>

      <input type="submit" value="Save" />
    </form>
  </body>
</html>

myMovieReviews/MOVIE/reviews/templates/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포스트 상세 정보</title>
  </head>

  <body>
    <h1><a href="{% url 'reviews:list' %}">myMoviereviews</a></h1>
    <h1>{{ review.title }}</h1>
    <p>개봉년도 {{ review.year }}년</p>
    <p>감독 {{ review.director }}</p>
    <p>주연 {{ review.actor }}</p>    
    <p>장르 {{ review.genre }}</p>
    <p>별점 {{ review.rating }}</p>
    <p>러닝타임 {{ review.runningTime }}</p>
    <p>{{ review.review | linebreaksbr }}</p>

    <a href="{% url 'reviews:update' review.id %}">수정</a>
    <a href="{% url 'reviews:delete' review.id %}">삭제</a>
 

  </body>
</html>

myMovieReviews/MOVIE/reviews/templates/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=divice-width" />
    <title>My Movie reviews</title>
  </head>
  <body>
    <h3><a href="{% url 'reviews:create'%}">Add a New release</a></h3>

    {%for review in reviews%}
    <h2><a href="{% url 'reviews:detail' review.id %}">{{ review.title }}</a></h2>
    <br />
    <p>개봉년도 {{review.year}}년</p>
    <p>장르 {{review.genre}}</p>
    <p>별점 {{review.rating}}</p>
    {%endfor%}
  </body>
</html>