piro16_Ajax_Pirostagram/PIROSTAGRAM/PIROSTAGRAM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),

]

piro16_Ajax_Pirostagram/PIROSTAGRAM/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post_new/', views.post_new, name='post_new'),
    path('like_ajax/', views.like_ajax, name='like_ajax'),
    path('delete_ajax/', views.delete_ajax, name='delete_ajax'),
    path('post_ajax/', views.post_ajax, name='post_ajax'),


]

piro16_Ajax_Pirostagram/PIROSTAGRAM/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    like = models.IntegerField()

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return self.content

piro16_Ajax_Pirostagram/PIROSTAGRAM/posts/forms.py
from django import forms
from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

piro16_Ajax_Pirostagram/PIROSTAGRAM/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm


# Create your views here.
def post_list(request):
    posts = Post.objects.all()
    order_comments = {}
    for p in posts:
        comments = Comment.objects.filter(post=p)
        order_comments[p] = comments
    ctx = {
        'order_comments': order_comments,
    }
    return render(request, 'posts/post_list.html', context=ctx)

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:post_list')
        else:
            ctx = {
                'form': form,
            }
            return render(request, 'posts/post_new.html', ctx)
    elif request.method == 'GET':
        form = PostForm()
        ctx = {
            'form': form,
        }
        return render(request, 'posts/post_new.html', ctx)


import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# {% csrf_token %}
@csrf_exempt
def like_ajax(request):
    req = json.loads(request.body)  
    post_id = req['id']

    post = Post.objects.get(id=post_id)

    post.like += 1
    
    post.save()

    return JsonResponse({'id' : post_id })  


# {% csrf_token %}
@csrf_exempt
def delete_ajax(request):
    req = json.loads(request.body) 
    comment_id = req['id']

    comment = Comment.objects.get(id=comment_id)

    comment.delete()

    return JsonResponse({'id' : comment_id })



# {% csrf_token %}
@csrf_exempt
def post_ajax(request):
    req = json.loads(request.body) 
    post_id = req['id']
    post_content = req['content']

    reply = Comment.objects.create(post=Post.objects.get(id=post_id), content=post_content)
    reply.save()
        

    return JsonResponse({'id' : post_id, 'content' : post_content, 'comment_id' : reply.id})

piro16_Ajax_Pirostagram/PIROSTAGRAM/PIROSTAGRAM/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajax</title>

    {% block extra_head %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'layout.css' %}">
    {% endblock %}
</head>
<body>
    <header>
        <div class="header__container">
            <div class="header__text">
                Pirostagram
            </div>
        </div>
        <div>
            <button><a href="{% url 'posts:post_new'%}">게시물 등록</a></button>
        </div>
    </header>
    
    {% block content %}
        <!-- 기본 내용 -->
    {% endblock %}

    {% block extra %}
    {% endblock %}
</body>
</html>

piro16_Ajax_Pirostagram/PIROSTAGRAM/posts/templates/posts/post_list.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <div class="main__container">
        {% for post, comments in order_comments.items %}
            <div class="card post__container post-id-{{ post.id }}">
                <div class="card-body">
                    <div class="card-title">{{ post.title }}</div>
                    <div class="card-text">{{ post.content }}</div>
                    <div id="post">
                        <textarea class="replyContent" placeholder="댓글 입력"></textarea>
                        <input type="button" value="게시" onclick="onClickPost({{ post.id }})">
                    </div>
                    <div id="comment">
                        {% for c in comments %}
                            <div class="comment-id-{{ c.id }}">
                                {{ c.content }}
                                <input type="button" value="삭제" onclick="onClickDelete({{ c.id }})">
                            </div>
                        {% endfor %}
                    </div>
                    <div class="btn btn-primary post__like" onclick="onClickLike({{ post.id }})">Like {{ post.like }}</div>
                    
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block extra %}

<script>
    const requestLike = new XMLHttpRequest();

    const onClickLike = (id) => {
        const url = "/like_ajax/";
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );
        requestLike.send(JSON.stringify({id: id})); // {'id': 1, 'type': 'like'}
    };

    const likeHandleResponse = () => {
        if (requestLike.status < 400) {
            const {id} = JSON.parse(requestLike.response);
            const element = document.querySelector(`.post-id-${id} .post__like`);
            const originHTML = element.innerHTML;       // 'like 0'
            const [buttonType, num] = originHTML.split(' ');    // ['like', '0']
            const count = Number(num) + 1;

            element.innerHTML = `${buttonType} ${count}`;   // 'like 1'
        }
    };

    requestLike.onreadystatechange = () => {
        if (requestLike.readyState === XMLHttpRequest.DONE) {
            likeHandleResponse();
        }
    };



    const requestDelete = new XMLHttpRequest();

    const onClickDelete = (id) => {
        const url = "/delete_ajax/";
        requestDelete.open("POST", url, true);
        requestDelete.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );
        requestDelete.send(JSON.stringify({id: id})); 
    };

    const deleteHandleResponse = () => {
        if (requestDelete.status < 400) {
            const {id} = JSON.parse(requestDelete.response);
            const element = document.querySelector(`.comment-id-${id}`);
            const originHTML = element.innerHTML;       
            element.remove()
        }
    };

    requestDelete.onreadystatechange = () => {
        if (requestDelete.readyState === XMLHttpRequest.DONE) {
            deleteHandleResponse();
        }
    };




    const requestPost = new XMLHttpRequest();

    const onClickPost = (id) => {
        const url = "/post_ajax/";
        requestPost.open("POST", url, true);
        requestPost.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );
        const content = document.querySelector(`.post-id-${id} .replyContent`).value;
        requestPost.send(JSON.stringify({id : id, content : content}));
    };

    const postHandleResponse = () => {
        if (requestPost.status < 400) {
            const {id, content, comment_id} = JSON.parse(requestPost.response);
            const newDiv = document.createElement('div');
            newDiv.innerHTML = '<div class="comment-id-'+comment_id+'">' +content+ '<input type="button" value="삭제" onclick="onClickDelete('+comment_id+')"></div>'
            document.querySelector(`.post-id-${id} #comment`).appendChild(newDiv);

            const postDiv = document.querySelector(`.post-id-${id} #post`);
            postDiv.innerHTML = '<textarea class="replyContent" placeholder="댓글 입력"></textarea> <input type="button" value="게시" onclick="onClickPost('+id+')">'
        }
    };

    requestPost.onreadystatechange = () => {
        if (requestPost.readyState === XMLHttpRequest.DONE) {
            postHandleResponse();
        }
    };





</script>








{% endblock %}

piro16_Ajax_Pirostagram/PIROSTAGRAM/posts/templates/posts/post_new.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <div class="form__container">
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>

            <input type="submit" value="submit">
        </form>
    </div>
{% endblock %}